spring:
  application:
    name: pharmacy2206814425
  datasource:
    url: jdbc:postgresql://localhost:5432/pharmacy2206814425
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create